# ---------------------------------------------------------------
# workflow: publish
#
# Perform on version tag push
#
# Signs and published artifacts to Maven Central
#
on:
  release:
    types: [published]

name: publish

jobs:
  publish:
    name: 'Publish Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish Release
        run: |
          ./gradlew publishToMavenLocal
