# ---------------------------------------------------------------
# workflow: publish
#
# Perform on all release:create events
#
# Signs and published artifacts to Maven Central
#
on:
  workflow_call:
    inputs:
      java-version:
        default: '17'
        description: JDK version
        required: false
        type: string
      java-distribution:
        default: 'corretto'
        description: JDK distribution
        required: false
        type: string
      dry-run:
        default: false
        description: If true, only publish locally
        required: false
        type: boolean

name: publish

jobs:
  publish:
    name: 'Publish Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java-version }} (${{ inputs.java-distribution }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - if: ${{ inputs.dry-run }}
        name: Publish Release (Local)
        run: ./gradlew publishToMavenLocal
      - if: ${{ !inputs.dry-run }}
        name: Publish Release (Maven Central)
        run: |
          export ORG_GRADLE_PROJECT_signingKey=$(echo -n "$GPG_SIGNING_KEY_BASE64" | base64 -d)
          ./gradlew publishToCentral closeAndReleaseCentralStagingRepository
        env:
          ORG_GRADLE_PROJECT_ossrhUserName: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhToken: ${{ secrets.OSSRH_TOKEN }}
          GPG_SIGNING_KEY_BASE64: ${{ secrets.GPG_SIGNING_KEY_BASE64 }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
