# ---------------------------------------------------------------
# workflow: publish
#
# Perform on all release:create events
#
# Signs and published artifacts to Maven Central
#
on:
  workflow_call:
    inputs:
      java-version:
        default: '17'
        description: JDK version
        required: false
        type: string

name: publish

jobs:
  publish:
    name: 'Publish Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish Release
        run: |
          ./gradlew publishToMavenLocal
