name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  # ---------------------------------------------------------------
  # job: release
  #
  # Manually invoke to rerun release-please
  #
  # * Creates and maintains "release PR"
  # * Creates release when the "release PR" is merged to "master"
  #
  # See: https://github.com/google-github-actions/release-please-action
  # See: https://github.com/googleapis/release-please
  #
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.5.0
        id: release
        with:
          include-v-in-tag: true
          release-type: simple
          extra-files: |
            build.gradle
            README.md
        outputs:
          release_created: ${{ steps.release.outputs.release_created }}
          tag_name: ${{ steps.release.outputs.tag_name }}

  publish:
    name: 'Publish Release'
    needs: [ release ]
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish Release
        run: |
          echo Tag: ${{ needs.release.outputs.tag_name }}
          ./gradlew publishToMavenLocal
