on:
  workflow_call:
    inputs:
      dry-run:
        default: false
        description: Only publish locally
        required: false
        type: boolean
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_TOKEN:
        required: true
      GPG_SIGNING_KEY_BASE64:
        required: true
      GPG_SIGNING_PASSPHRASE:
        required: true
      SEMANTIC_TOKEN:
        required: true

name: release

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: ${{ inputs.dry-run || false }}
          tag_format: ${version}
          extra_plugins: |
            @commitlint/config-conventional
            @google/semantic-release-replace-plugin
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
      - name: Release version
        if: steps.release.outputs.new_release_published == 'true'
        run: |
          echo "published?: ${{ steps.release.outputs.new_release_published }}"
          echo "new version: ${{ steps.release.outputs.new_release_version }}"
          echo "orig ref: ${{ github.ref }}"
          echo "new ref: ${{ steps.release.outputs.new_release_git_head }}"
    outputs:
      release_created: ${{ steps.release.outputs.new_release_published }}
      release_version: ${{ steps.release.outputs.new_release_version }}
      new_release_git_head: ${{ steps.release.outputs.new_release_git_head }}

  publish:
    needs: [ release ]
    name: Publish
    if: ${{ needs.release.outputs.release_created == 'true' }}
    uses: mxenabled/path-tools/.github/workflows/publish.yml@master
    with:
      ref: ${{ needs.release.outputs.new_release_git_head }}
    secrets:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SIGNING_KEY_BASE64: ${{ secrets.GPG_SIGNING_KEY_BASE64 }}
      GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
